version: "3.7" 

services: 
    default:
        build: ./apps/default
        container_name: default
        ports: 
            - 80:3000
        volumes: 
            - './apps/default:/etc/nginx/conf.d'
        networks: 
            - network

    frontend:
        build: ./apps/frontend
        ports:
            - 90:5000
        networks:
            - network

#    admin: 
#        build: ./admin
#        container_name: admin 
    
#    articles: 
 #       build ./articles
 #       container_name: articles
    
   # auth:

   # study:

   # users: 
    
    

    # without processes and extradata in MVP

networks: 
    network:
        driver: bridge
    

