version: "3.7" 

services: 
    default:
        build: ./apps/default
        container_name: default
        ports: 
            - 3000:80
        #volumes: 
        #    - '/apps/default:/etc/nginx/conf.d'
        networks: 
            - network

    frontend:
        build: ./apps/frontend
        container_name: frontend
        env_file: 
            - frontend-variables.env
        ports:
            - 3001:3000
        #volumes: 
        #    - './apps/frontend/src:/usr/src/nuxt-app'
        networks:
            - network

    admin: 
        build: ./apps/admin
        container_name: admin 
        networks:
            - network

    articles: 
        build: ./apps/articles
        container_name: articles
        networks:
            - network

    auth:
        build: ./apps/auth
        container_name: auth
        networks:
            - network

    study:
        build: ./apps/study
        container_name: study
        networks:
            - network

    users: 
        build: ./apps/users
        container_name: users
        networks:
            - network



    # without processes and extradata in MVP

networks: 
    network:
        driver: bridge
    

