version: "3.7"

services:
  router:
    restart: always
    build: ./apps/server/router
    container_name: router
    environment: 
      - PORT=${PORT_ROUTER_INTERNAL}
      - HOST=${HOST_GENERAL}
    ports:
      - ${PORT_ROUTER_EXTERNAL}:${PORT_ROUTER_INTERNAL}
    depends_on:
      - api-auth 
      - api-content
      - api-users
      - api-extra 
      - api-stuff
      - front-public
      - front-processes
      - front-admin
    links:
      - api-auth 
      - api-content
      - api-users
      - api-extra 
      - api-stuff
      - front-public
      - front-processes
      - front-admin
    networks:
      - network

  api-auth:
    build: ./apps/server/api-auth
    container_name: api-auth
    environment: 
      - PORT=${PORT_API-AUTH_INTERNAL}
      - HOST=${HOST_GENERAL}
    volumes:
      - ./apps/server/api-auth/src:/usr/src:rw
    ports:
      - ${PORT_API-AUTH_EXTERNAL}:${PORT_API-AUTH_INTERNAL}
    networks:
      - network







  other:
    build: ./apps/other
    container_name: other
    environment: 
      - PORT=${PORT_OTHER_INTERNAL}
      - HOST=${HOST_GENERAL}
    volumes:
      - ./apps/other/src:/usr/src:rw
    ports:
      - ${PORT_OTHER_EXTERNAL}:${PORT_OTHER_INTERNAL}
    networks:
      - network

  study:
    build: ./apps/study
    container_name: study
    environment: 
      - PORT=${PORT_STUDY_INTERNAL}
      - HOST=${HOST_GENERAL}
    volumes:
      - ./apps/study/src:/usr/src:rw
    ports:
      - ${PORT_STUDY_EXTERNAL}:${PORT_STUDY_INTERNAL}
    networks:
      - network

  extra:
    build: ./apps/extra
    container_name: extra
    environment: 
      - PORT=${PORT_EXTRA_INTERNAL}
      - HOST=${HOST_GENERAL}
    volumes:
      - ./apps/extra/src:/usr/src:rw
    ports:
      - ${PORT_EXTRA_EXTERNAL}:${PORT_EXTRA_INTERNAL}
    networks:
      - network

  

  users:
    build: ./apps/users
    container_name: users
    environment: 
      - PORT=${PORT_USERS_INTERNAL}
      - HOST=${HOST_GENERAL}
    volumes:
      - ./apps/users/src:/usr/src:rw
    ports:
      - ${PORT_USERS_EXTERNAL}:${PORT_USERS_INTERNAL}
    networks:
      - network

  frontend:
    build: ./apps/frontend
    container_name: frontend
    environment:
      - NUXT_PORT=${PORT_FRONTEND_INTERNAL} 
      - NUXT_HOST=${HOST_NUXT_INTERNAL}
    volumes:
      - ./apps/frontend/src:/usr/src:rw
    ports:
      - ${PORT_FRONTEND_EXTERNAL}:${PORT_FRONTEND_INTERNAL}
    networks:
      - network

  processes:
    build: ./apps/processes
    container_name: processes
    environment: 
      - PORT=${PORT_PROCESSES_INTERNAL}
      - HOST=${HOST_GENERAL}
    volumes:
      - ./apps/processes/src:/usr/src:rw
    ports:
      - ${PORT_PROCESSES_EXTERNAL}:${PORT_PROCESSES_INTERNAL}
    networks:
      - network

  admin:
    build: ./apps/admin
    container_name: admin
    environment: 
      - PORT=${PORT_AUTH_INTERNAL}
      - HOST=${HOST_GENERAL}
    volumes:
      - ./apps/admin/src:/usr/src:rw
    ports:
      - ${PORT_ADMIN_EXTERNAL}:${PORT_ADMIN_INTERNAL}
    environment:
      - PORT=${PORT_ADMIN_INTERNAL}
    networks:
      - network

networks:
  network:
    driver: bridge
