version: "3.7"

services:
  default:
    restart: always
    build: ./apps/default
    container_name: default
    environment: 
      - PORT=${PORT_DEFAULT_INTERNAL}
      - HOST=${HOST_GENERAL}
    ports:
      - ${PORT_DEFAULT_EXTERNAL}:${PORT_DEFAULT_INTERNAL}
    depends_on:
      - frontend
      - admin
      - other
      - auth
      - study
      - users
      - extra
      - processes
    links:
      - frontend
      - admin
      - other
      - auth
      - study
      - users
      - extra
      - processes
    networks:
      - network

  other:
    build: ./apps/other
    container_name: other
    environment: 
      - PORT=${PORT_OTHER_INTERNAL}
      - HOST=${HOST_GENERAL}
    volumes:
      - ./apps/other/src:/usr/src:rw
    ports:
      - ${PORT_OTHER_EXTERNAL}:${PORT_OTHER_INTERNAL}
    networks:
      - network

  study:
    build: ./apps/study
    container_name: study
    environment: 
      - PORT=${PORT_STUDY_INTERNAL}
      - HOST=${HOST_GENERAL}
    volumes:
      - ./apps/study/src:/usr/src:rw
    ports:
      - ${PORT_STUDY_EXTERNAL}:${PORT_STUDY_INTERNAL}
    networks:
      - network

  extra:
    build: ./apps/extra
    container_name: extra
    environment: 
      - PORT=${PORT_EXTRA_INTERNAL}
      - HOST=${HOST_GENERAL}
    volumes:
      - ./apps/extra/src:/usr/src:rw
    ports:
      - ${PORT_EXTRA_EXTERNAL}:${PORT_EXTRA_INTERNAL}
    networks:
      - network

  auth:
    build: ./apps/auth
    container_name: auth
    environment: 
      - PORT=${PORT_AUTH_INTERNAL}
      - HOST=${HOST_GENERAL}
    volumes:
      - ./apps/auth/src:/usr/src:rw
    ports:
      - ${PORT_AUTH_EXTERNAL}:${PORT_AUTH_INTERNAL}
    networks:
      - network

  users:
    build: ./apps/users
    container_name: users
    environment: 
      - PORT=${PORT_USERS_INTERNAL}
      - HOST=${HOST_GENERAL}
    volumes:
      - ./apps/users/src:/usr/src:rw
    ports:
      - ${PORT_USERS_EXTERNAL}:${PORT_USERS_INTERNAL}
    networks:
      - network

  frontend:
    build: ./apps/frontend
    container_name: frontend
    environment:
      - NUXT_PORT=${PORT_FRONTEND_INTERNAL} 
      - NUXT_HOST=${HOST_NUXT_INTERNAL}
    volumes:
      - ./apps/frontend/src:/usr/src:rw
    ports:
      - ${PORT_FRONTEND_EXTERNAL}:${PORT_FRONTEND_INTERNAL}
    networks:
      - network

  processes:
    build: ./apps/processes
    container_name: processes
    environment: 
      - PORT=${PORT_PROCESSES_INTERNAL}
      - HOST=${HOST_GENERAL}
    volumes:
      - ./apps/processes/src:/usr/src:rw
    ports:
      - ${PORT_PROCESSES_EXTERNAL}:${PORT_PROCESSES_INTERNAL}
    networks:
      - network

  admin:
    build: ./apps/admin
    container_name: admin
    environment: 
      - PORT=${PORT_AUTH_INTERNAL}
      - HOST=${HOST_GENERAL}
    volumes:
      - ./apps/admin/src:/usr/src:rw
    ports:
      - ${PORT_ADMIN_EXTERNAL}:${PORT_ADMIN_INTERNAL}
    environment:
      - PORT=${PORT_ADMIN_INTERNAL}
    networks:
      - network

networks:
  network:
    driver: bridge
