version: "3.7" 

services: 
    default:
        depends_on: 
            - frontend
            - admin
            - other
            - auth
            - study
            - users
            - extra
            - processes
        restart: always
        build: ./apps/default
        container_name: default
        ports: 
            - 3000:80
        links:
            - frontend
            - admin
            - other 
            - auth
            - study
            - users
            - extra
            - processes
        networks: 
            - network 

    frontend:
        build: ./apps/frontend
        container_name: frontend
        env_file: 
            - ./envs/frontend-variables.env
        ports:
            - 5000:5000
        networks:
            - network

    admin: 
        build: ./apps/admin
        container_name: admin 
        env_file: 
            - ./envs/admin-variables.env
        volumes:
            - ./apps/admin/src:/usr/src:rw
        ports: 
            - 7000:7000
        networks:
            - network

    other: 
        build: ./apps/other
        container_name: other
        env_file: 
            - ./envs/other-variables.env
        volumes:
            - ./apps/other/src:/usr/src:rw
        ports: 
            - 3100:3100
        networks:
            - network

    auth:
        build: ./apps/auth
        container_name: auth
        env_file: 
            - ./envs/auth-variables.env
        volumes:
            - ./apps/auth/src:/usr/src:rw
        ports: 
            - 4000:4000
        networks:
            - network

    study:
        build: ./apps/study
        container_name: study
        env_file: 
            - ./envs/study-variables.env
        volumes:
            - ./apps/study/src:/usr/src:rw
        ports: 
            - 3200:3200
        networks:
            - network

    users: 
        build: ./apps/users
        container_name: users
        env_file: 
            - ./envs/users-variables.env
        volumes:
            - ./apps/users/src:/usr/src:rw
        ports: 
            - 4100:4100
        networks:
            - network

    extra:
        build: ./apps/extra
        container_name: extra
        env_file: 
            - ./envs/extra-variables.env
        volumes:
            - ./apps/extra/src:/usr/src:rw
        ports: 
            - 3300:3300
        networks: 
            - network
        
    processes:
        build: ./apps/processes
        container_name: processes
        env_file: 
            - ./envs/processes-variables.env
        volumes:
            - ./apps/processes/src:/usr/src:rw
        ports: 
            - 9000:9000
        networks: 
            - network
            



    # without processes and extradata in MVP

networks: 
    network:
        driver: bridge
        


