version: "3.7" 

services: 
    default:
        build: ./apps/default
        container_name: default
        ports: 
            - 3000:80
        #volumes: 
        #    - '/apps/default:/etc/nginx/conf.d'
        networks: 
            - network
    frontend:
        build: ./apps/frontend
        container_name: frontend
        env_file: 
            - frontend-variables.env
        ports:
            - 3001:3000
        networks:
            - network

#    admin: 
#        build: ./admin
#        container_name: admin 
    
#    articles: 
 #       build ./articles
 #       container_name: articles
    
   # auth:

   # study:

   # users: 
    
    

    # without processes and extradata in MVP

networks: 
    network:
        driver: bridge
    

